St/interop final
HorizenOfficial/libevm pull request #20
Opened 2023-10-11 08:17 UTC by saratnt

This PR contains all the modifications needed for implementing the interoperability between EVM and native smart contracts.
It requires HorizenOfficial/go-ethereum 1.0.0-snapshot version (PR: https://github.com/HorizenOfficial/go-ethereum/pull/5)

2023-10-23 08:08 UTC, saratnt commented on native/interop/json.go
> +	// make sure to throw errors incase unknown fields are passed, do not silently ignore this
Done

2023-10-23 08:28 UTC, paolocappelletti requested changes

2023-10-23 10:16 UTC, saratnt commented on libevm/src/main/java/io/horizen/evm/EvmContext.java
> +    public BigInteger gasPrice;
I think it is probably OK, but just to be safe I have encapsulated the fields so to make it possible to add checks on assignment in the future.

2023-10-23 10:59 UTC, saratnt commented on libevm/src/main/java/io/horizen/evm/InvocationResult.java
> +package io.horizen.evm;
Done

2023-10-24 08:16 UTC, paologalligit approved these changes

2023-11-02 14:08 UTC, paolocappelletti approved these changes

2023-11-03 15:14 UTC, merged